import { IMAGES } from "./images";

export const DEMO_PRODUCTS = [
    // ── Sportswear ──
    {
        id: 1, slug: "custom-elite-basketball-jersey", title: "Custom Elite Basketball Jersey",
        category: "Sports Wear", subCategory: "Jerseys", shortDescription: "Premium moisture-wicking basketball jersey.",
        description: "Our signature heavyweight basketball jersey is crafted from 180GSM micro-mesh, delivering exceptional durability and a premium feel that your team will love. Designed specifically for professional and amateur leagues, each piece can be fully customized with your logo, artwork, or numbering through sublimation or tackle twill.",
        mainImage: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=85",
        samplePrice: "35.00", material: "180 GSM Micro Mesh Polyester",
        availableSizes: JSON.stringify(["S", "M", "L", "XL", "2XL", "3XL"]),
        availableColors: JSON.stringify(["Red", "Blue", "Black", "White", "Custom"]),
        isFeatured: true, freeShipping: false, isActive: true,
        startingPrice: "$35.00", moq: "50 pcs",
        images: [{ id: 101, imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "24.50", label: "Startup", sortOrder: 0 },
            { id: 2, minQty: 101, maxQty: 500, pricePerUnit: "17.50", label: "Scale", sortOrder: 1 },
        ],
    },
    {
        id: 2, slug: "sublimated-soccer-kit", title: "Pro Sublimated Soccer Kit",
        category: "Sports Wear", subCategory: "Team Kits", shortDescription: "Fully sublimated custom soccer uniforms.",
        description: "High performance soccer kits with fully custom sublimation. Breathable interlock polyester designed for 90 minutes of intense action.",
        mainImage: "https://images.unsplash.com/photo-1518091043644-c1d44570a2c9?w=800&q=85",
        samplePrice: "40.00", material: "160 GSM Interlock Polyester",
        availableSizes: JSON.stringify(["S", "M", "L", "XL", "2XL"]),
        availableColors: JSON.stringify(["Custom Team Colors"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$40.00", moq: "50 pcs",
        images: [{ id: 102, imageUrl: "https://images.unsplash.com/photo-1518091043644-c1d44570a2c9?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "28.00", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 3, slug: "compression-base-layer", title: "Athletic Compression Base Layer",
        category: "Sports Wear", subCategory: "Compression Wear", shortDescription: "4-way stretch compression wear for all sports.",
        description: "Private label compression gear for your athletic brand. Moisture-wicking, anti-odor, and 4-way stretch.",
        mainImage: "https://images.unsplash.com/photo-1581636625402-29f2a0dfbef4?w=800&q=85",
        samplePrice: "25.00", material: "Spandex/Polyester Blend 220 GSM",
        availableSizes: JSON.stringify(["XS", "S", "M", "L", "XL", "2XL"]),
        availableColors: JSON.stringify(["Black", "White", "Navy", "Charcoal"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$25.00", moq: "50 pcs",
        images: [{ id: 103, imageUrl: "https://images.unsplash.com/photo-1581636625402-29f2a0dfbef4?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "15.00", label: "Startup", sortOrder: 0 },
        ],
    },
    // ── Hunting Wear ──
    {
        id: 4, slug: "waterproof-hunting-jacket", title: "Tactical Waterproof Hunting Jacket",
        category: "Hunting Wear", subCategory: "Hunting Jackets", shortDescription: "Silent shell waterproof jacket in custom camo.",
        description: "B2B manufacturing for silent waterproof hunting jackets. Engineered for the field.",
        mainImage: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=85",
        samplePrice: "85.00", material: "Softshell with DWR coating",
        availableSizes: JSON.stringify(["M", "L", "XL", "2XL", "3XL"]),
        availableColors: JSON.stringify(["Multicam", "Real Tree", "Olive Drab"]),
        isFeatured: true, freeShipping: false, isActive: true,
        startingPrice: "$85.00", moq: "50 pcs",
        images: [{ id: 104, imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "59.50", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 5, slug: "ripstop-cargo-pants", title: "Reinforced Ripstop Hunting Cargo Pants",
        category: "Hunting Wear", subCategory: "Hunting Pants", shortDescription: "Tough ripstop pants with articulated knees.",
        description: "Durable ripstop cargo pants designed for the wild. Reinforced seat and knees.",
        mainImage: "https://images.unsplash.com/photo-1550346059-59eb4df42d8a?w=800&q=85",
        samplePrice: "55.00", material: "Cotton/Poly Ripstop 280 GSM",
        availableSizes: JSON.stringify(["30", "32", "34", "36", "38", "40"]),
        availableColors: JSON.stringify(["Khaki", "Coyote Brown", "Multicam"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$55.00", moq: "50 pcs",
        images: [{ id: 105, imageUrl: "https://images.unsplash.com/photo-1550346059-59eb4df42d8a?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "38.50", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 6, slug: "camo-fleece-pullover", title: "Thermal Camo Fleece Pullover",
        category: "Hunting Wear", subCategory: "Camo Gear", shortDescription: "Mid-layer fleece for cold morning hunts.",
        description: "Warm, silent, microfleece layer for hunting brands. Keeps you warm when it matters.",
        mainImage: "https://images.unsplash.com/photo-1553531384-397c80973a0b?w=800&q=85",
        samplePrice: "45.00", material: "Microfleece 300 GSM",
        availableSizes: JSON.stringify(["S", "M", "L", "XL", "2XL"]),
        availableColors: JSON.stringify(["Woodland Camo", "Digital Camo"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$45.00", moq: "50 pcs",
        images: [{ id: 106, imageUrl: "https://images.unsplash.com/photo-1553531384-397c80973a0b?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "31.50", label: "Startup", sortOrder: 0 },
        ],
    },
    // ── Streetwear ──
    {
        id: 7, slug: "heavyweight-oversized-hoodie", title: "450GSM Heavyweight Oversized Hoodie",
        category: "Streetwear", subCategory: "Hoodies", shortDescription: "Premium drop-shoulder boxy fit hoodie.",
        description: "Premium blank and custom heavyweight hoodies for streetwear brands. 450GSM French terry cotton.",
        mainImage: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=85",
        samplePrice: "45.00", material: "450 GSM French Terry Cotton",
        availableSizes: JSON.stringify(["S", "M", "L", "XL", "2XL"]),
        availableColors: JSON.stringify(["Black", "Heather Grey", "Vintage Wash", "Cream"]),
        isFeatured: true, freeShipping: false, isActive: true,
        startingPrice: "$45.00", moq: "50 pcs",
        images: [{ id: 107, imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "31.50", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 8, slug: "vintage-wash-graphic-tee", title: "Vintage Wash Graphic Tee",
        category: "Streetwear", subCategory: "T-Shirts", shortDescription: "Acid-washed oversized tee ready for screen printing.",
        description: "Acid washed blanks and custom printed vintage tees. Highly sought after drop-shoulder fit.",
        mainImage: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=85",
        samplePrice: "22.00", material: "280 GSM Ring-Spun Cotton",
        availableSizes: JSON.stringify(["XS", "S", "M", "L", "XL", "2XL"]),
        availableColors: JSON.stringify(["Washed Black", "Washed Grey", "Washed Olive"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$22.00", moq: "50 pcs",
        images: [{ id: 108, imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "14.50", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 9, slug: "nylon-cargo-joggers", title: "Utility Nylon Cargo Joggers",
        category: "Streetwear", subCategory: "Cargo Pants", shortDescription: "Tech-inspired streetwear joggers with multiple pockets.",
        description: "High-quality streetwear cargo pants wholesale manufacturing. DWR coating and bungee cuffs.",
        mainImage: "https://plus.unsplash.com/premium_photo-1673356301535-224a0dcdcbca?w=800&q=85",
        samplePrice: "38.00", material: "Nylon/Spandex Blend with DWR",
        availableSizes: JSON.stringify(["S", "M", "L", "XL"]),
        availableColors: JSON.stringify(["Black", "Navy", "Olive"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$38.00", moq: "50 pcs",
        images: [{ id: 109, imageUrl: "https://plus.unsplash.com/premium_photo-1673356301535-224a0dcdcbca?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "26.50", label: "Startup", sortOrder: 0 },
        ],
    },
    // ── Security Uniforms ──
    {
        id: 10, slug: "tactical-security-polo", title: "Moisture-Wicking Tactical Security Polo",
        category: "Security Uniforms", shortDescription: "Professional guard polo with mic loops.",
        description: "Durable and breathable polos for security professionals. Features epaulets and pen pockets.",
        mainImage: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=85",
        samplePrice: "24.00", material: "200 GSM Pique Moisture-Wicking",
        availableSizes: JSON.stringify(["S", "M", "L", "XL", "2XL", "3XL", "4XL"]),
        availableColors: JSON.stringify(["Black", "Navy", "White"]),
        isFeatured: true, freeShipping: false, isActive: true,
        startingPrice: "$24.00", moq: "50 pcs",
        images: [{ id: 110, imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "16.80", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 11, slug: "hi-vis-security-jacket", title: "High-Visibility Patrol Jacket",
        category: "Security Uniforms", shortDescription: "Weatherproof jacket with 3M reflective tape.",
        description: "Safety outerwear built for extreme guard duties. Fully waterproof and fleece-lined.",
        mainImage: "https://images.unsplash.com/photo-1542662059-e1ae67a1496a?w=800&q=85",
        samplePrice: "65.00", material: "300D Oxford Polyester with PU Coating",
        availableSizes: JSON.stringify(["M", "L", "XL", "2XL", "3XL"]),
        availableColors: JSON.stringify(["Neon Yellow/Black", "Neon Orange/Navy"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$65.00", moq: "50 pcs",
        images: [{ id: 111, imageUrl: "https://images.unsplash.com/photo-1542662059-e1ae67a1496a?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "45.50", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 12, slug: "security-combat-trousers", title: "Reinforced Guard Combat Trousers",
        category: "Security Uniforms", shortDescription: "Teflon-coated durable pants with baton pocket.",
        description: "Professional guard trousers with teflon finish. Stain-resistant and incredibly durable.",
        mainImage: "https://images.unsplash.com/photo-1623868662657-3f3efd684824?w=800&q=85",
        samplePrice: "35.00", material: "Poly/Cotton Twill with Teflon",
        availableSizes: JSON.stringify(["30", "32", "34", "36", "38", "40", "42"]),
        availableColors: JSON.stringify(["Black", "Navy"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$35.00", moq: "50 pcs",
        images: [{ id: 112, imageUrl: "https://images.unsplash.com/photo-1623868662657-3f3efd684824?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "24.50", label: "Startup", sortOrder: 0 },
        ],
    },
    // ── Tech Wear ──
    {
        id: 13, slug: "modular-tech-jacket", title: "Modular Waterproof Techwear Jacket",
        category: "Tech Wear", shortDescription: "Fidlock buckles, waterproof zips, multiple strapping points.",
        description: "High-end conceptual techwear manufacturing for innovative brands. 3-layer GORE-TEX compatible shell.",
        mainImage: "https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=85",
        samplePrice: "120.00", material: "3-Layer GORE-TEX Compatible Shell",
        availableSizes: JSON.stringify(["S", "M", "L", "XL"]),
        availableColors: JSON.stringify(["Matte Black", "Gunmetal Grey"]),
        isFeatured: true, freeShipping: false, isActive: true,
        startingPrice: "$120.00", moq: "50 pcs",
        images: [{ id: 113, imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "84.00", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 14, slug: "tactical-chest-rig", title: "Urban Tactical Chest Rig Bag",
        category: "Tech Wear", shortDescription: "Laser cut molle, sleek urban design.",
        description: "Wholesale manufacturing of techwear bags and rigs. FIDLOCK magnetic closures and 500D Cordura.",
        mainImage: "https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?w=800&q=85",
        samplePrice: "45.00", material: "500D Cordura Nylon",
        availableSizes: JSON.stringify(["One Size"]),
        availableColors: JSON.stringify(["Black", "Silver Geo"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$45.00", moq: "50 pcs",
        images: [{ id: 114, imageUrl: "https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "31.50", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 15, slug: "articulated-tech-cargo", title: "Articulated Techwear Cargo Pants",
        category: "Tech Wear", shortDescription: "Pre-curved knees and expanding pocket system.",
        description: "Advanced pattern making for techwear brands. DWR coated stretch nylon.",
        mainImage: "https://images.unsplash.com/photo-1622519407650-3cb98286aa54?w=800&q=85",
        samplePrice: "65.00", material: "Stretch Nylon Ripstop",
        availableSizes: JSON.stringify(["28", "30", "32", "34", "36"]),
        availableColors: JSON.stringify(["Black", "Olive", "Charcoal"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$65.00", moq: "50 pcs",
        images: [{ id: 115, imageUrl: "https://images.unsplash.com/photo-1622519407650-3cb98286aa54?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "45.50", label: "Startup", sortOrder: 0 },
        ],
    },
    // ── Ski Wear ──
    {
        id: 16, slug: "alpine-pro-snow-jacket", title: "Alpine Pro 20K Snow Jacket",
        category: "Ski Wear", subCategory: "Ski Jackets", shortDescription: "20k/20k waterproof and breathable alpine jacket.",
        description: "High-end ski apparel manufacturing with 20K waterproofing and Primaloft insulation.",
        mainImage: "https://images.unsplash.com/photo-1551524164-687a55dd1126?w=800&q=85",
        samplePrice: "140.00", material: "20K Poly Shell + Primaloft Insulation",
        availableSizes: JSON.stringify(["S", "M", "L", "XL", "2XL"]),
        availableColors: JSON.stringify(["Neon Pink", "Ice Blue", "Black/White Bold"]),
        isFeatured: true, freeShipping: false, isActive: true,
        startingPrice: "$140.00", moq: "50 pcs",
        images: [{ id: 116, imageUrl: "https://images.unsplash.com/photo-1551524164-687a55dd1126?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "98.00", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 17, slug: "insulated-snow-bib", title: "Insulated Freeride Snow Bib",
        category: "Ski Wear", subCategory: "Ski Pants", shortDescription: "Full coverage bib with sealed zippers and powder cuffs.",
        description: "Durable snow bibs and overalls for freeride and park snowboarding.",
        mainImage: "https://images.unsplash.com/photo-1610443420456-c2ba79471f54?w=800&q=85",
        samplePrice: "110.00", material: "15K/15K Waterproof Oxford",
        availableSizes: JSON.stringify(["XS", "S", "M", "L", "XL"]),
        availableColors: JSON.stringify(["Mustard Yellow", "Black", "Forest Green"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$110.00", moq: "50 pcs",
        images: [{ id: 117, imageUrl: "https://images.unsplash.com/photo-1610443420456-c2ba79471f54?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "77.00", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 18, slug: "merino-base-layer", title: "Merino Wool Snow Base Layer Set",
        category: "Ski Wear", subCategory: "Base Layers", shortDescription: "Natural odor resistant, temperature regulating set.",
        description: "Custom merino wool thermals for winter sports. Prevents odors and keeps you warm.",
        mainImage: "https://images.unsplash.com/photo-1520113412521-996ff6d7734a?w=800&q=85",
        samplePrice: "60.00", material: "100% Merino Wool 210 GSM",
        availableSizes: JSON.stringify(["S", "M", "L", "XL"]),
        availableColors: JSON.stringify(["Black", "Charcoal Marl"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$60.00", moq: "50 pcs",
        images: [{ id: 118, imageUrl: "https://images.unsplash.com/photo-1520113412521-996ff6d7734a?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "42.00", label: "Startup", sortOrder: 0 },
        ],
    },
    // ── Martial Arts Wear ──
    {
        id: 19, slug: "custom-bjj-gi", title: "Custom BJJ Gi",
        category: "Martial Arts Wear", subCategory: "BJJ Gis", shortDescription: "Pearl weave 550GSM, IBJJF compliant.",
        description: "Custom premium BJJ gi for academies and brands.",
        mainImage: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800&q=85",
        samplePrice: "65.00", material: "Pearl Weave 550GSM",
        availableSizes: JSON.stringify(["A0", "A1", "A2", "A3", "A4", "A5"]),
        availableColors: JSON.stringify(["White", "Blue", "Black"]),
        isFeatured: true, freeShipping: false, isActive: true,
        startingPrice: "$65.00", moq: "50 pcs",
        images: [{ id: 119, imageUrl: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "45.00", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 20, slug: "custom-mma-rashguard", title: "Custom MMA Rashguard",
        category: "Martial Arts Wear", subCategory: "Rashguards", shortDescription: "Nylon-spandex 200GSM, full sublimation.",
        description: "IBJJF ranked rashguards fully sublimated.",
        mainImage: "https://images.unsplash.com/photo-1599058917212-97d142bdfb39?w=800&q=85",
        samplePrice: "22.00", material: "200 GSM Nylon/Spandex",
        availableSizes: JSON.stringify(["XS", "S", "M", "L", "XL", "2XL"]),
        availableColors: JSON.stringify(["Custom Ranked Colors"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$22.00", moq: "50 pcs",
        images: [{ id: 120, imageUrl: "https://images.unsplash.com/photo-1599058917212-97d142bdfb39?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "14.00", label: "Startup", sortOrder: 0 },
        ],
    },
    {
        id: 21, slug: "mma-fight-shorts", title: "MMA Fight Shorts",
        category: "Martial Arts Wear", subCategory: "MMA Shorts", shortDescription: "4-way lightweight stretch, velcro closure.",
        description: "Durable and flexible fight shorts designed for striking and grappling.",
        mainImage: "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&q=85",
        samplePrice: "28.00", material: "Microfiber Stretch",
        availableSizes: JSON.stringify(["30", "32", "34", "36", "38"]),
        availableColors: JSON.stringify(["Custom Artwork"]),
        isFeatured: false, freeShipping: false, isActive: true,
        startingPrice: "$28.00", moq: "50 pcs",
        images: [{ id: 121, imageUrl: "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&q=85", sortOrder: 0 }],
        slabs: [
            { id: 1, minQty: 50, maxQty: 100, pricePerUnit: "19.00", label: "Startup", sortOrder: 0 },
        ],
    },
];
